<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('categories')->insert([
            // Expense Categories
            [
                'id' => 1,
                'company_id' => 1,
                'name' => 'Office Supplies',
                'type' => 'expense',
                'color' => '#3498db',
                'icon' => 'fas fa-paperclip',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 2,
                'company_id' => 1,
                'name' => 'Software & Licenses',
                'type' => 'expense',
                'color' => '#9b59b6',
                'icon' => 'fas fa-laptop-code',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 3,
                'company_id' => 1,
                'name' => 'Hardware & Equipment',
                'type' => 'expense',
                'color' => '#e74c3c',
                'icon' => 'fas fa-server',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 4,
                'company_id' => 1,
                'name' => 'Travel & Transportation',
                'type' => 'expense',
                'color' => '#f39c12',
                'icon' => 'fas fa-car',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 5,
                'company_id' => 1,
                'name' => 'Professional Services',
                'type' => 'expense',
                'color' => '#2ecc71',
                'icon' => 'fas fa-handshake',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            
            // Income Categories
            [
                'id' => 6,
                'company_id' => 1,
                'name' => 'IT Services',
                'type' => 'income',
                'color' => '#1abc9c',
                'icon' => 'fas fa-tools',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 7,
                'company_id' => 1,
                'name' => 'Consulting',
                'type' => 'income',
                'color' => '#34495e',
                'icon' => 'fas fa-user-tie',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 8,
                'company_id' => 1,
                'name' => 'Software Development',
                'type' => 'income',
                'color' => '#8e44ad',
                'icon' => 'fas fa-code',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 9,
                'company_id' => 1,
                'name' => 'Managed Services',
                'type' => 'income',
                'color' => '#27ae60',
                'icon' => 'fas fa-shield-alt',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            
            // Ticket Categories
            [
                'id' => 10,
                'company_id' => 1,
                'name' => 'Hardware Issue',
                'type' => 'ticket',
                'color' => '#e67e22',
                'icon' => 'fas fa-wrench',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 11,
                'company_id' => 1,
                'name' => 'Software Issue',
                'type' => 'ticket',
                'color' => '#3498db',
                'icon' => 'fas fa-bug',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 12,
                'company_id' => 1,
                'name' => 'Network Issue',
                'type' => 'ticket',
                'color' => '#e74c3c',
                'icon' => 'fas fa-network-wired',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 13,
                'company_id' => 1,
                'name' => 'User Request',
                'type' => 'ticket',
                'color' => '#2ecc71',
                'icon' => 'fas fa-user-plus',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 14,
                'company_id' => 1,
                'name' => 'Security Issue',
                'type' => 'ticket',
                'color' => '#c0392b',
                'icon' => 'fas fa-shield-alt',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            
            // Quote Categories
            [
                'id' => 15,
                'company_id' => 1,
                'name' => 'IT Services',
                'type' => 'quote',
                'color' => '#20c997',
                'icon' => 'fas fa-tools',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 16,
                'company_id' => 1,
                'name' => 'Telecom Services',
                'type' => 'quote',
                'color' => '#17a2b8',
                'icon' => 'fas fa-phone',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 17,
                'company_id' => 1,
                'name' => 'Equipment Sales',
                'type' => 'quote',
                'color' => '#fd7e14',
                'icon' => 'fas fa-server',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 18,
                'company_id' => 1,
                'name' => 'Professional Services',
                'type' => 'quote',
                'color' => '#6f42c1',
                'icon' => 'fas fa-user-tie',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 19,
                'company_id' => 1,
                'name' => 'Maintenance Contracts',
                'type' => 'quote',
                'color' => '#28a745',
                'icon' => 'fas fa-wrench',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            
            // Product Categories
            [
                'id' => 20,
                'company_id' => 1,
                'name' => 'Hardware',
                'type' => 'product',
                'color' => '#6f42c1',
                'icon' => 'fas fa-microchip',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 21,
                'company_id' => 1,
                'name' => 'Software',
                'type' => 'product',
                'color' => '#007bff',
                'icon' => 'fas fa-code',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 22,
                'company_id' => 1,
                'name' => 'Licenses',
                'type' => 'product',
                'color' => '#ffc107',
                'icon' => 'fas fa-key',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 23,
                'company_id' => 1,
                'name' => 'Accessories',
                'type' => 'product',
                'color' => '#17a2b8',
                'icon' => 'fas fa-plug',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 24,
                'company_id' => 1,
                'name' => 'Services',
                'type' => 'product',
                'color' => '#28a745',
                'icon' => 'fas fa-cogs',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            
            // Invoice Categories
            [
                'id' => 25,
                'company_id' => 1,
                'name' => 'Professional Services',
                'type' => 'invoice',
                'color' => '#fd7e14',
                'icon' => 'fas fa-user-tie',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 26,
                'company_id' => 1,
                'name' => 'Equipment',
                'type' => 'invoice',
                'color' => '#dc3545',
                'icon' => 'fas fa-server',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 27,
                'company_id' => 1,
                'name' => 'Recurring Services',
                'type' => 'invoice',
                'color' => '#28a745',
                'icon' => 'fas fa-redo',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 28,
                'company_id' => 1,
                'name' => 'One-time Services',
                'type' => 'invoice',
                'color' => '#6c757d',
                'icon' => 'fas fa-clock',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            
            // Recurring Categories
            [
                'id' => 29,
                'company_id' => 1,
                'name' => 'Monthly Services',
                'type' => 'recurring',
                'color' => '#6c757d',
                'icon' => 'fas fa-calendar',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 30,
                'company_id' => 1,
                'name' => 'Quarterly Services',
                'type' => 'recurring',
                'color' => '#17a2b8',
                'icon' => 'fas fa-calendar-alt',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 31,
                'company_id' => 1,
                'name' => 'Annual Contracts',
                'type' => 'recurring',
                'color' => '#ffc107',
                'icon' => 'fas fa-calendar-check',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            
            // Asset Categories
            [
                'id' => 32,
                'company_id' => 1,
                'name' => 'Servers',
                'type' => 'asset',
                'color' => '#17a2b8',
                'icon' => 'fas fa-server',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 33,
                'company_id' => 1,
                'name' => 'Workstations',
                'type' => 'asset',
                'color' => '#007bff',
                'icon' => 'fas fa-desktop',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 34,
                'company_id' => 1,
                'name' => 'Network Equipment',
                'type' => 'asset',
                'color' => '#28a745',
                'icon' => 'fas fa-network-wired',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 35,
                'company_id' => 1,
                'name' => 'Mobile Devices',
                'type' => 'asset',
                'color' => '#fd7e14',
                'icon' => 'fas fa-mobile-alt',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
            [
                'id' => 36,
                'company_id' => 1,
                'name' => 'Software Assets',
                'type' => 'asset',
                'color' => '#6f42c1',
                'icon' => 'fas fa-code',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'archived_at' => null,
            ],
        ]);
    }
}