{{-- Asset Reports --}}
<div class="space-y-6">
    <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <flux:card><div class="space-y-1"><flux:text size="sm" class="text-zinc-500">Total Assets</flux:text><flux:heading size="xl">{{ $this->assetStats['total_assets'] ?? 0 }}</flux:heading></div></flux:card>
        <flux:card><div class="space-y-1"><flux:text size="sm" class="text-zinc-500">Active Assets</flux:text><flux:heading size="xl">{{ $this->assetStats['active_assets'] ?? 0 }}</flux:heading></div></flux:card>
        <flux:card><div class="space-y-1"><flux:text size="sm" class="text-zinc-500">Warranty Expiring</flux:text><flux:heading size="xl">{{ $this->assetStats['warranty_expiring'] ?? 0 }}</flux:heading></div></flux:card>
        <flux:card><div class="space-y-1"><flux:text size="sm" class="text-zinc-500">Maintenance Due</flux:text><flux:heading size="xl">{{ $this->assetStats['maintenance_due'] ?? 0 }}</flux:heading></div></flux:card>
    </div>
    <div class="grid gap-6 lg:grid-cols-2">
        <flux:card><flux:heading size="lg" class="mb-4">Assets by Type</flux:heading><div x-data="{chart:null,initChart(){this.chart=new Chart(this.$refs.canvas,{type:'doughnut',data:{labels:{{json_encode($this->assetsByType['labels']??[])}},datasets:[{data:{{json_encode($this->assetsByType['data']??[])}},backgroundColor:['#3b82f6','#10b981','#f59e0b','#8b5cf6','#ec4899']}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:true,position:'bottom'}}}})}}" x-init="setTimeout(()=>initChart(),100)"><canvas x-ref="canvas" class="w-full" height="250"></canvas></div></flux:card>
        <flux:card><flux:heading size="lg" class="mb-4">Assets by Status</flux:heading><div x-data="{chart:null,initChart(){this.chart=new Chart(this.$refs.canvas,{type:'bar',data:{labels:{{json_encode($this->assetsByStatus['labels']??[])}},datasets:[{data:{{json_encode($this->assetsByStatus['data']??[])}},backgroundColor:['#10b981','#3b82f6','#f59e0b','#ef4444']}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true}}}})}}" x-init="setTimeout(()=>initChart(),100)"><canvas x-ref="canvas" class="w-full" height="250"></canvas></div></flux:card>
    </div>
    <flux:card><flux:heading size="lg" class="mb-4">Asset Inventory</flux:heading>@if($this->assetList->count()>0)<div class="overflow-x-auto"><table class="w-full"><thead class="border-b border-zinc-200 dark:border-zinc-700"><tr><th class="text-left py-3 text-sm">Name</th><th class="text-left py-3 text-sm">Type</th><th class="text-left py-3 text-sm">Status</th><th class="text-left py-3 text-sm">Warranty</th></tr></thead><tbody class="divide-y divide-zinc-200 dark:divide-zinc-700">@foreach($this->assetList as $asset)<tr><td class="py-3"><flux:text size="sm">{{$asset->name}}</flux:text></td><td class="py-3"><flux:text size="sm">{{$asset->type??'N/A'}}</flux:text></td><td class="py-3"><flux:badge size="sm">{{ucfirst($asset->status??'unknown')}}</flux:badge></td><td class="py-3"><flux:text size="sm">{{$asset->warranty_expire?$asset->warranty_expire->format('M j, Y'):'N/A'}}</flux:text></td></tr>@endforeach</tbody></table></div>@else<flux:text class="text-center py-8 text-zinc-500">No assets found.</flux:text>@endif</flux:card>
</div>
