{{-- Contract Reports --}}
<div class="space-y-6">
    <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <flux:card><div class="space-y-1"><flux:text size="sm" class="text-zinc-500">Active Contracts</flux:text><flux:heading size="xl">{{ $this->contractStats['active_contracts'] ?? 0 }}</flux:heading></div></flux:card>
        <flux:card><div class="space-y-1"><flux:text size="sm" class="text-zinc-500">Total Value</flux:text><flux:heading size="xl">${{ number_format($this->contractStats['total_value'] ?? 0, 0) }}</flux:heading></div></flux:card>
        <flux:card><div class="space-y-1"><flux:text size="sm" class="text-zinc-500">Expiring Soon</flux:text><flux:heading size="xl">{{ $this->contractStats['expiring_soon'] ?? 0 }}</flux:heading></div></flux:card>
        <flux:card><div class="space-y-1"><flux:text size="sm" class="text-zinc-500">Pending Signatures</flux:text><flux:heading size="xl">{{ $this->contractStats['pending_signatures'] ?? 0 }}</flux:heading></div></flux:card>
    </div>
    <div class="grid gap-6 lg:grid-cols-2">
        <flux:card><flux:heading size="lg" class="mb-4">Contracts by Status</flux:heading><div x-data="{chart:null,initChart(){this.chart=new Chart(this.$refs.canvas,{type:'doughnut',data:{labels:{{json_encode($this->contractsByStatus['labels']??[])}},datasets:[{data:{{json_encode($this->contractsByStatus['data']??[])}},backgroundColor:['#10b981','#3b82f6','#f59e0b','#ef4444','#8b5cf6']}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:true,position:'bottom'}}}})}}" x-init="setTimeout(()=>initChart(),100)"><canvas x-ref="canvas" class="w-full" height="250"></canvas></div></flux:card>
        <flux:card><flux:heading size="lg" class="mb-4">Renewal Pipeline</flux:heading><div x-data="{chart:null,initChart(){this.chart=new Chart(this.$refs.canvas,{type:'bar',data:{labels:{{json_encode($this->renewalPipeline['labels']??[])}},datasets:[{label:'Contracts',data:{{json_encode($this->renewalPipeline['data']??[])}},backgroundColor:'rgba(99,102,241,0.8)'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true}}}})}}" x-init="setTimeout(()=>initChart(),100)"><canvas x-ref="canvas" class="w-full" height="250"></canvas></div></flux:card>
    </div>
    <flux:card><flux:heading size="lg" class="mb-4">Recent Contracts</flux:heading>@if($this->contractList->count()>0)<div class="overflow-x-auto"><table class="w-full"><thead class="border-b border-zinc-200 dark:border-zinc-700"><tr><th class="text-left py-3 text-sm">Name</th><th class="text-left py-3 text-sm">Status</th><th class="text-left py-3 text-sm">Value</th><th class="text-left py-3 text-sm">End Date</th></tr></thead><tbody class="divide-y divide-zinc-200 dark:divide-zinc-700">@foreach($this->contractList as $contract)<tr><td class="py-3"><flux:text size="sm">{{$contract->name??'Contract'}}</flux:text></td><td class="py-3"><flux:badge size="sm">{{ucfirst($contract->status??'unknown')}}</flux:badge></td><td class="py-3"><flux:text size="sm">${{number_format($contract->contract_value??0,2)}}</flux:text></td><td class="py-3"><flux:text size="sm">{{$contract->end_date?$contract->end_date->format('M j, Y'):'N/A'}}</flux:text></td></tr>@endforeach</tbody></table></div>@else<flux:text class="text-center py-8 text-zinc-500">No contracts found.</flux:text>@endif</flux:card>
</div>
