{{-- Project Reports --}}
<div class="space-y-6">
    <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <flux:card><div class="space-y-1"><flux:text size="sm" class="text-zinc-500">Active Projects</flux:text><flux:heading size="xl">{{ $this->projectStats['active_projects'] ?? 0 }}</flux:heading></div></flux:card>
        <flux:card><div class="space-y-1"><flux:text size="sm" class="text-zinc-500">Completed</flux:text><flux:heading size="xl">{{ $this->projectStats['completed_projects'] ?? 0 }}</flux:heading></div></flux:card>
        <flux:card><div class="space-y-1"><flux:text size="sm" class="text-zinc-500">On Schedule</flux:text><flux:heading size="xl">{{ $this->projectStats['on_schedule_percent'] ?? 0 }}%</flux:heading></div></flux:card>
        <flux:card><div class="space-y-1"><flux:text size="sm" class="text-zinc-500">Budget Used</flux:text><flux:heading size="xl">{{ $this->projectStats['budget_utilization'] ?? 0 }}%</flux:heading></div></flux:card>
    </div>
    <div class="grid gap-6 lg:grid-cols-2">
        <flux:card><flux:heading size="lg" class="mb-4">Projects by Status</flux:heading><div x-data="{chart:null,initChart(){this.chart=new Chart(this.$refs.canvas,{type:'doughnut',data:{labels:{{json_encode($this->projectsByStatus['labels']??[])}},datasets:[{data:{{json_encode($this->projectsByStatus['data']??[])}},backgroundColor:['#10b981','#3b82f6','#f59e0b','#8b5cf6']}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:true,position:'bottom'}}}})}}" x-init="setTimeout(()=>initChart(),100)"><canvas x-ref="canvas" class="w-full" height="250"></canvas></div></flux:card>
        <flux:card><flux:heading size="lg" class="mb-4">Project Progress</flux:heading><div x-data="{chart:null,initChart(){this.chart=new Chart(this.$refs.canvas,{type:'bar',data:{labels:{{json_encode($this->projectProgress['labels']??[])}},datasets:[{label:'Progress %',data:{{json_encode($this->projectProgress['data']??[])}},backgroundColor:'rgba(99,102,241,0.8)'}]},options:{indexAxis:'y',responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{beginAtZero:true,max:100}}}})}}" x-init="setTimeout(()=>initChart(),100)"><canvas x-ref="canvas" class="w-full" height="250"></canvas></div></flux:card>
    </div>
    <flux:card><flux:heading size="lg" class="mb-4">Recent Projects</flux:heading>@if($this->projectList->count()>0)<div class="overflow-x-auto"><table class="w-full"><thead class="border-b border-zinc-200 dark:border-zinc-700"><tr><th class="text-left py-3 text-sm">Name</th><th class="text-left py-3 text-sm">Status</th><th class="text-left py-3 text-sm">Progress</th><th class="text-left py-3 text-sm">Due Date</th></tr></thead><tbody class="divide-y divide-zinc-200 dark:divide-zinc-700">@foreach($this->projectList as $project)<tr><td class="py-3"><flux:text size="sm">{{$project->name}}</flux:text></td><td class="py-3"><flux:badge size="sm">{{ucfirst($project->status??'unknown')}}</flux:badge></td><td class="py-3"><flux:text size="sm">{{$project->progress_percentage??0}}%</flux:text></td><td class="py-3"><flux:text size="sm">{{$project->due?$project->due->format('M j, Y'):'N/A'}}</flux:text></td></tr>@endforeach</tbody></table></div>@else<flux:text class="text-center py-8 text-zinc-500">No projects found.</flux:text>@endif</flux:card>
</div>
