{{-- Quote Reports --}}
<div class="space-y-6">
    <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <flux:card><div class="space-y-1"><flux:text size="sm" class="text-zinc-500">Total Quotes</flux:text><flux:heading size="xl">{{ $this->quoteStats['total_quotes'] ?? 0 }}</flux:heading></div></flux:card>
        <flux:card><div class="space-y-1"><flux:text size="sm" class="text-zinc-500">Pending Quotes</flux:text><flux:heading size="xl">{{ $this->quoteStats['pending_quotes'] ?? 0 }}</flux:heading></div></flux:card>
        <flux:card><div class="space-y-1"><flux:text size="sm" class="text-zinc-500">Acceptance Rate</flux:text><flux:heading size="xl">{{ $this->quoteStats['acceptance_rate'] ?? 0 }}%</flux:heading></div></flux:card>
        <flux:card><div class="space-y-1"><flux:text size="sm" class="text-zinc-500">Total Value</flux:text><flux:heading size="xl">${{ number_format($this->quoteStats['total_value'] ?? 0, 0) }}</flux:heading></div></flux:card>
    </div>
    <div class="grid gap-6 lg:grid-cols-2">
        <flux:card><flux:heading size="lg" class="mb-4">Quotes by Status</flux:heading><div x-data="{chart:null,initChart(){this.chart=new Chart(this.$refs.canvas,{type:'doughnut',data:{labels:{{json_encode($this->quotesByStatus['labels']??[])}},datasets:[{data:{{json_encode($this->quotesByStatus['data']??[])}},backgroundColor:['#3b82f6','#10b981','#ef4444','#f59e0b','#8b5cf6']}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:true,position:'bottom'}}}})}}" x-init="setTimeout(()=>initChart(),100)"><canvas x-ref="canvas" class="w-full" height="250"></canvas></div></flux:card>
        <flux:card><flux:heading size="lg" class="mb-4">Quote Trends</flux:heading><div x-data="{chart:null,initChart(){this.chart=new Chart(this.$refs.canvas,{type:'line',data:{labels:{{json_encode($this->quoteTrends['labels']??[])}},datasets:[{label:'Sent',data:{{json_encode($this->quoteTrends['sent']??[])}},borderColor:'rgb(59,130,246)',backgroundColor:'rgba(59,130,246,0.1)',tension:0.4},{label:'Accepted',data:{{json_encode($this->quoteTrends['accepted']??[])}},borderColor:'rgb(16,185,129)',backgroundColor:'rgba(16,185,129,0.1)',tension:0.4}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:true,position:'bottom'}},scales:{y:{beginAtZero:true}}}})}}" x-init="setTimeout(()=>initChart(),100)"><canvas x-ref="canvas" class="w-full" height="250"></canvas></div></flux:card>
    </div>
    <flux:card><flux:heading size="lg" class="mb-4">Recent Quotes</flux:heading>@if($this->quoteList->count()>0)<div class="overflow-x-auto"><table class="w-full"><thead class="border-b border-zinc-200 dark:border-zinc-700"><tr><th class="text-left py-3 text-sm">Title</th><th class="text-left py-3 text-sm">Status</th><th class="text-right py-3 text-sm">Amount</th><th class="text-left py-3 text-sm">Date</th></tr></thead><tbody class="divide-y divide-zinc-200 dark:divide-zinc-700">@foreach($this->quoteList as $quote)<tr><td class="py-3"><flux:text size="sm">{{$quote->title??'Quote #'.$quote->id}}</flux:text></td><td class="py-3"><flux:badge size="sm" :color="$quote->status==='Accepted'?'green':($quote->status==='Declined'?'red':'blue')">{{$quote->status}}</flux:badge></td><td class="py-3 text-right"><flux:text size="sm" class="font-semibold">${{number_format($quote->amount??0,2)}}</flux:text></td><td class="py-3"><flux:text size="sm">{{$quote->date->format('M j, Y')}}</flux:text></td></tr>@endforeach</tbody></table></div>@else<flux:text class="text-center py-8 text-zinc-500">No quotes found.</flux:text>@endif</flux:card>
</div>
