<?php

namespace Database\Factories;

use App\Models\ClientDocument;
use Illuminate\Database\Eloquent\Factories\Factory;

class ClientDocumentFactory extends Factory
{
    protected $model = ClientDocument::class;

    public function definition(): array
    {
        return [
            'company_id' => 1,
            'type' => $this->faker->numberBetween(1, 5),
            'category' => $this->faker->optional()->word,
            'subcategory' => $this->faker->optional()->word,
            'title' => $this->faker->words(3, true),
            'description' => $this->faker->optional()->sentence,
            'filename' => $this->faker->words(3, true),
            'original_filename' => $this->faker->words(3, true),
            'mime_type' => $this->faker->numberBetween(1, 5),
            'extension' => $this->faker->optional()->word,
            'file_size' => $this->faker->optional()->word,
            'storage_path' => $this->faker->optional()->word,
            'storage_disk' => $this->faker->optional()->word,
            'file_hash' => $this->faker->optional()->word,
            'checksum' => $this->faker->optional()->word,
            'is_system_generated' => $this->faker->boolean(70),
            'is_template_based' => $this->faker->boolean(70),
            'is_signed' => $this->faker->boolean(70),
            'signatures' => $this->faker->optional()->word,
            'is_encrypted' => $this->faker->boolean(70),
            'encryption_method' => $this->faker->optional()->word,
            'visibility' => $this->faker->optional()->word,
            'requires_authentication' => $this->faker->optional()->word,
            'download_enabled' => $this->faker->boolean(70),
            'view_enabled' => $this->faker->boolean(70),
            'print_enabled' => $this->faker->boolean(70),
            'share_enabled' => $this->faker->boolean(70),
            'access_permissions' => $this->faker->optional()->word,
            'download_restrictions' => $this->faker->optional()->word,
            'security_level' => $this->faker->optional()->word,
            'contains_pii' => $this->faker->optional()->word,
            'contains_phi' => $this->faker->optional()->word,
            'contains_financial_data' => $this->faker->optional()->word,
            'compliance_tags' => $this->faker->optional()->word,
            'requires_retention' => $this->faker->optional()->word,
            'retention_until' => $this->faker->optional()->word,
            'auto_delete_enabled' => $this->faker->boolean(70),
            'version' => $this->faker->optional()->word,
            'is_current_version' => $this->faker->boolean(70),
            'version_notes' => $this->faker->optional()->sentence,
            'superseded_at' => $this->faker->optional()->dateTimeBetween('-1 year', 'now'),
            'superseded_by' => $this->faker->optional()->word,
            'related_model_type' => $this->faker->numberBetween(1, 5),
            'processing_status' => 'active',
            'processing_error' => $this->faker->optional()->word,
            'text_extracted' => $this->faker->optional()->word,
            'extracted_text' => $this->faker->optional()->word,
            'metadata_extracted' => $this->faker->optional()->word,
            'thumbnail_generated' => $this->faker->optional()->word,
            'thumbnail_path' => $this->faker->optional()->word,
            'page_count' => $this->faker->optional()->word,
            'email_delivery_enabled' => $this->faker->safeEmail,
            'email_recipients' => $this->faker->safeEmail,
            'last_emailed_at' => $this->faker->safeEmail,
            'portal_notification_sent' => $this->faker->optional()->word,
            'portal_notification_sent_at' => $this->faker->optional()->dateTimeBetween('-1 year', 'now'),
            'requires_acknowledgment' => $this->faker->optional()->word,
            'acknowledged_at' => $this->faker->optional()->dateTimeBetween('-1 year', 'now'),
            'acknowledgment_method' => $this->faker->optional()->word,
            'view_count' => $this->faker->optional()->word,
            'download_count' => $this->faker->optional()->word,
            'print_count' => $this->faker->optional()->word,
            'share_count' => $this->faker->optional()->word,
            'first_viewed_at' => $this->faker->optional()->dateTimeBetween('-1 year', 'now'),
            'last_viewed_at' => $this->faker->optional()->dateTimeBetween('-1 year', 'now'),
            'first_downloaded_at' => $this->faker->optional()->dateTimeBetween('-1 year', 'now'),
            'last_downloaded_at' => $this->faker->optional()->dateTimeBetween('-1 year', 'now'),
            'access_history' => $this->faker->optional()->word,
            'external_source' => $this->faker->optional()->word,
            'external_metadata' => $this->faker->optional()->word,
            'sync_enabled' => $this->faker->boolean(70),
            'last_synced_at' => $this->faker->optional()->dateTimeBetween('-1 year', 'now'),
            'sync_error' => $this->faker->optional()->word,
            'tags' => $this->faker->optional()->word,
            'labels' => $this->faker->optional()->word,
            'reference_number' => $this->faker->optional()->word,
            'document_date' => $this->faker->optional()->dateTimeBetween('-1 year', 'now'),
            'received_date' => $this->faker->optional()->dateTimeBetween('-1 year', 'now'),
            'effective_date' => $this->faker->optional()->dateTimeBetween('-1 year', 'now'),
            'expiry_date' => $this->faker->optional()->dateTimeBetween('-1 year', 'now'),
            'show_in_portal' => $this->faker->optional()->word,
            'portal_sort_order' => $this->faker->optional()->word,
            'portal_display_name' => $this->faker->words(3, true),
            'portal_description' => $this->faker->optional()->sentence,
            'portal_icon' => $this->faker->optional()->word,
            'portal_settings' => $this->faker->optional()->word,
            'workflow_status' => 'active',
            'approved_by' => $this->faker->optional()->word,
            'approved_at' => $this->faker->optional()->dateTimeBetween('-1 year', 'now'),
            'approval_notes' => $this->faker->optional()->sentence,
            'requires_approval' => $this->faker->optional()->word,
            'approval_workflow' => $this->faker->optional()->word,
            'custom_fields' => $this->faker->optional()->word,
            'metadata' => $this->faker->optional()->word,
            'notes' => $this->faker->optional()->sentence,
            'client_notes' => $this->faker->optional()->sentence,
            'status' => 'active',
            'archived_at' => $this->faker->optional()->dateTimeBetween('-1 year', 'now'),
            'deletion_reason' => $this->faker->optional()->word,
            'uploaded_by' => $this->faker->optional()->word,
            'updated_by' => $this->faker->optional()->dateTimeBetween('-1 year', 'now')
        ];
    }
}
