<?php

namespace Database\Factories;

use App\Models\ClientDocument;
use Illuminate\Database\Eloquent\Factories\Factory;

class ClientDocumentFactory extends Factory
{
    protected $model = ClientDocument::class;

    public function definition(): array
    {
        return [
            'company_id' => 1,
            'type' => null,
            'category' => null,
            'subcategory' => null,
            'title' => null,
            'description' => $this->faker->sentence,
            'filename' => $this->faker->words(3, true),
            'original_filename' => $this->faker->words(3, true),
            'mime_type' => null,
            'extension' => null,
            'file_size' => null,
            'storage_path' => null,
            'storage_disk' => null,
            'file_hash' => null,
            'checksum' => null,
            'is_system_generated' => true,
            'is_template_based' => true,
            'is_signed' => true,
            'signatures' => null,
            'is_encrypted' => true,
            'encryption_method' => null,
            'visibility' => null,
            'requires_authentication' => null,
            'download_enabled' => null,
            'view_enabled' => null,
            'print_enabled' => null,
            'share_enabled' => null,
            'access_permissions' => null,
            'download_restrictions' => null,
            'security_level' => null,
            'contains_pii' => null,
            'contains_phi' => null,
            'contains_financial_data' => null,
            'compliance_tags' => null,
            'requires_retention' => null,
            'retention_until' => null,
            'auto_delete_enabled' => null,
            'version' => null,
            'is_current_version' => true,
            'version_notes' => null,
            'superseded_at' => null,
            'superseded_by' => null,
            'related_model_type' => null,
            'processing_status' => 'active',
            'processing_error' => null,
            'text_extracted' => null,
            'extracted_text' => null,
            'metadata_extracted' => null,
            'thumbnail_generated' => null,
            'thumbnail_path' => null,
            'page_count' => null,
            'email_delivery_enabled' => $this->faker->safeEmail,
            'email_recipients' => $this->faker->safeEmail,
            'last_emailed_at' => $this->faker->safeEmail,
            'portal_notification_sent' => null,
            'portal_notification_sent_at' => null,
            'requires_acknowledgment' => null,
            'acknowledged_at' => null,
            'acknowledgment_method' => null,
            'view_count' => null,
            'download_count' => null,
            'print_count' => null,
            'share_count' => null,
            'first_viewed_at' => null,
            'last_viewed_at' => null,
            'first_downloaded_at' => null,
            'last_downloaded_at' => null,
            'access_history' => null,
            'external_source' => null,
            'external_metadata' => null,
            'sync_enabled' => null,
            'last_synced_at' => null,
            'sync_error' => null,
            'tags' => null,
            'labels' => null,
            'reference_number' => null,
            'document_date' => null,
            'received_date' => null,
            'effective_date' => null,
            'expiry_date' => null,
            'show_in_portal' => null,
            'portal_sort_order' => null,
            'portal_display_name' => $this->faker->words(3, true),
            'portal_description' => $this->faker->sentence,
            'portal_icon' => null,
            'portal_settings' => null,
            'workflow_status' => 'active',
            'approved_by' => null,
            'approved_at' => null,
            'approval_notes' => null,
            'requires_approval' => null,
            'approval_workflow' => null,
            'custom_fields' => null,
            'metadata' => null,
            'notes' => null,
            'client_notes' => null,
            'status' => 'active',
            'archived_at' => null,
            'deletion_reason' => null,
            'uploaded_by' => null,
            'updated_by' => null
        ];
    }
}
