<?php

namespace Database\Factories\Domains\Core\Models;

use App\Domains\Core\Models\PortalNotification;
use Illuminate\Database\Eloquent\Factories\Factory;

class PortalNotificationFactory extends Factory
{
    protected $model = PortalNotification::class;

    public function definition(): array
    {
        return [
            'company_id' => \App\Domains\Company\Models\Company::factory(),
            'client_id' => \App\Domains\Client\Models\Client::factory(),
            'type' => $this->faker->randomElement(['info', 'warning', 'error', 'success', 'update']),
            'category' => $this->faker->optional()->word,
            'priority' => $this->faker->randomElement(['low', 'normal', 'high', 'urgent']),
            'title' => $this->faker->words(3, true),
            'message' => $this->faker->sentence,
            'description' => $this->faker->optional()->sentence,
            'data' => json_encode([]),
            'icon' => $this->faker->optional()->word,
            'color' => $this->faker->optional()->word,
            'action_url' => $this->faker->optional()->url,
            'action_text' => $this->faker->optional()->words(3, true),
            'show_in_portal' => $this->faker->boolean(80),
            'send_email' => $this->faker->boolean(70),
            'send_sms' => $this->faker->boolean(30),
            'send_push' => $this->faker->boolean(20),
            'delivery_channels' => $this->faker->optional(0.5)->passthrough(json_encode(['email', 'sms', 'push'])),
            'email_subject' => $this->faker->sentence,
            'email_body' => $this->faker->optional()->paragraph,
            'email_template' => $this->faker->optional()->word,
            'email_sent_at' => $this->faker->optional(0.5)->dateTimeBetween('-1 year', 'now'),
            'email_delivered' => $this->faker->optional(0.5)->boolean,
            'email_error' => $this->faker->optional()->sentence,
            'sms_message' => $this->faker->optional()->sentence,
            'sms_sent_at' => $this->faker->optional(0.5)->dateTimeBetween('-1 year', 'now'),
            'sms_delivered' => $this->faker->optional(0.5)->boolean,
            'sms_error' => $this->faker->optional()->sentence,
            'push_title' => $this->faker->words(3, true),
            'push_body' => $this->faker->optional()->sentence,
            'push_data' => $this->faker->optional(0.5)->passthrough(json_encode(['key' => 'value'])),
            'push_sent_at' => $this->faker->optional(0.5)->dateTimeBetween('-1 year', 'now'),
            'push_delivered' => $this->faker->optional(0.5)->boolean,
            'push_error' => $this->faker->optional()->sentence,
            'status' => $this->faker->randomElement(['pending', 'sent', 'delivered', 'read', 'failed', 'cancelled']),
            'is_read' => $this->faker->boolean(70),
            'read_at' => $this->faker->optional(0.5)->dateTimeBetween('-1 year', 'now'),
            'is_dismissed' => $this->faker->boolean(70),
            'dismissed_at' => $this->faker->optional(0.5)->dateTimeBetween('-1 year', 'now'),
            'requires_action' => $this->faker->boolean(),
            'action_completed' => $this->faker->boolean(50),
            'action_completed_at' => $this->faker->optional(0.5)->dateTimeBetween('-1 year', 'now'),
            'scheduled_at' => $this->faker->optional(0.5)->dateTimeBetween('-1 year', 'now'),
            'expires_at' => $this->faker->optional(0.5)->dateTimeBetween('-1 year', 'now'),
            'is_recurring' => $this->faker->boolean(70),
            'recurring_pattern' => $this->faker->optional()->randomElement(['daily', 'weekly', 'monthly', 'quarterly', 'yearly']),
            'next_occurrence' => $this->faker->optional(0.5)->dateTimeBetween('now', '+1 year'),
            'target_conditions' => $this->faker->optional(0.5)->passthrough(json_encode(['condition' => 'value'])),
            'personalization_data' => $this->faker->optional(0.5)->passthrough(json_encode(['key' => 'value'])),
            'language' => 'en',
            'timezone' => $this->faker->optional()->timezone,
            'related_model_type' => $this->faker->optional()->word,
            'group_key' => $this->faker->optional()->word,
            'thread_position' => $this->faker->optional()->numberBetween(1, 10),
            'is_summary' => $this->faker->boolean(70),
            'tracking_data' => $this->faker->optional(0.5)->passthrough(json_encode(['key' => 'value'])),
            'view_count' => $this->faker->numberBetween(0, 100),
            'first_viewed_at' => $this->faker->optional(0.5)->dateTimeBetween('-1 year', 'now'),
            'last_viewed_at' => $this->faker->optional(0.5)->dateTimeBetween('-1 year', 'now'),
            'click_count' => $this->faker->numberBetween(0, 100),
            'first_clicked_at' => $this->faker->optional(0.5)->dateTimeBetween('-1 year', 'now'),
            'last_clicked_at' => $this->faker->optional(0.5)->dateTimeBetween('-1 year', 'now'),
            'variant' => $this->faker->optional()->word,
            'experiment_data' => $this->faker->optional(0.5)->passthrough(json_encode(['key' => 'value'])),
            'requires_acknowledgment' => $this->faker->boolean(),
            'acknowledged_at' => $this->faker->optional(0.5)->dateTimeBetween('-1 year', 'now'),
            'acknowledgment_method' => $this->faker->optional()->word,
            'audit_trail' => $this->faker->optional(0.5)->passthrough(json_encode(['action' => 'log'])),
            'respects_do_not_disturb' => $this->faker->boolean(80),
            'client_preferences' => $this->faker->optional(0.5)->passthrough(json_encode(['preference' => 'value'])),
            'can_be_disabled' => $this->faker->boolean(),
            'frequency_limit' => $this->faker->optional()->word,
            'source_system' => $this->faker->optional()->word,
            'webhook_data' => $this->faker->optional(0.5)->passthrough(json_encode(['webhook' => 'data'])),
            'trigger_webhooks' => $this->faker->boolean(40),
            'metadata' => json_encode([]),
            'custom_fields' => $this->faker->optional(0.5)->passthrough(json_encode(['field' => 'value'])),
            'internal_notes' => $this->faker->optional()->sentence,
            'created_by' => \App\Domains\Core\Models\User::factory(),
            'updated_by' => null
        ];
    }
}
