#!/bin/bash
cd /opt/nestogy
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\User\b/App\\Domains\\Core\\Models\\User/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Role\b/App\\Domains\\Core\\Models\\Role/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Permission\b/App\\Domains\\Core\\Models\\Permission/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Setting\b/App\\Domains\\Core\\Models\\Setting/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Tag\b/App\\Domains\\Core\\Models\\Tag/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Document\b/App\\Domains\\Core\\Models\\Document/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\DashboardWidget\b/App\\Domains\\Core\\Models\\DashboardWidget/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\CustomQuickAction\b/App\\Domains\\Core\\Models\\CustomQuickAction/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\NotificationPreference\b/App\\Domains\\Core\\Models\\NotificationPreference/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\PortalNotification\b/App\\Domains\\Core\\Models\\PortalNotification/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\InAppNotification\b/App\\Domains\\Core\\Models\\InAppNotification/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\MailTemplate\b/App\\Domains\\Core\\Models\\MailTemplate/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\AuditLog\b/App\\Domains\\Core\\Models\\AuditLog/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\AnalyticsSnapshot\b/App\\Domains\\Core\\Models\\AnalyticsSnapshot/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\UserSetting\b/App\\Domains\\Core\\Models\\UserSetting/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Company\b/App\\Domains\\Company\\Models\\Company/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Account\b/App\\Domains\\Company\\Models\\Account/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\AccountHold\b/App\\Domains\\Company\\Models\\AccountHold/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\CompanyHierarchy\b/App\\Domains\\Company\\Models\\CompanyHierarchy/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\CompanyCustomization\b/App\\Domains\\Company\\Models\\CompanyCustomization/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\CompanyMailSettings\b/App\\Domains\\Company\\Models\\CompanyMailSettings/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\CrossCompanyUser\b/App\\Domains\\Company\\Models\\CrossCompanyUser/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\SubsidiaryPermission\b/App\\Domains\\Company\\Models\\SubsidiaryPermission/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\CreditApplication\b/App\\Domains\\Company\\Models\\CreditApplication/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Asset\b/App\\Domains\\Asset\\Models\\Asset/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Client\b/App\\Domains\\Client\\Models\\Client/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Contact\b/App\\Domains\\Client\\Models\\ClientContact/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Address\b/App\\Domains\\Client\\Models\\Address/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Location\b/App\\Domains\\Client\\Models\\Location/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\ClientCalendarEvent\b/App\\Domains\\Client\\Models\\ClientCalendarEvent/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\ClientCertificate\b/App\\Domains\\Client\\Models\\ClientCertificate/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\ClientCredential\b/App\\Domains\\Client\\Models\\ClientCredential/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\ClientFile\b/App\\Domains\\Client\\Models\\ClientFile/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\ClientDomain\b/App\\Domains\\Client\\Models\\ClientDomain/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\ClientLicense\b/App\\Domains\\Client\\Models\\ClientLicense/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\ClientNetwork\b/App\\Domains\\Client\\Models\\ClientNetwork/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\ClientQuote\b/App\\Domains\\Client\\Models\\ClientQuote/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\ClientRack\b/App\\Domains\\Client\\Models\\ClientRack/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\ClientRecurringInvoice\b/App\\Domains\\Client\\Models\\ClientRecurringInvoice/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\ClientService\b/App\\Domains\\Client\\Models\\ClientService/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\ClientTrip\b/App\\Domains\\Client\\Models\\ClientTrip/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\ClientVendor\b/App\\Domains\\Client\\Models\\ClientVendor/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Network\b/App\\Domains\\Client\\Models\\ClientNetwork/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\CommunicationLog\b/App\\Domains\\Client\\Models\\CommunicationLog/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\ClientCredit\b/App\\Domains\\Financial\\Models\\ClientCredit/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\ClientCreditApplication\b/App\\Domains\\Financial\\Models\\ClientCreditApplication/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Quote\b/App\\Domains\\Financial\\Models\\Quote/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\QuoteItem\b/App\\Domains\\Financial\\Models\\QuoteItem/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Invoice\b/App\\Domains\\Financial\\Models\\Invoice/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Payment\b/App\\Domains\\Financial\\Models\\Payment/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\PaymentMethod\b/App\\Domains\\Financial\\Models\\PaymentMethod/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\PaymentApplication\b/App\\Domains\\Financial\\Models\\PaymentApplication/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Expense\b/App\\Domains\\Financial\\Models\\Expense/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\ExpenseCategory\b/App\\Domains\\Financial\\Models\\Category/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Category\b/App\\Domains\\Financial\\Models\\Category/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\AutoPayment\b/App\\Domains\\Financial\\Models\\AutoPayment/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Recurring\b/App\\Domains\\Financial\\Models\\Recurring/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Product\b/App\\Domains\\Product\\Models\\Product/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\ProductBundle\b/App\\Domains\\Product\\Models\\ProductBundle/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Bundle\b/App\\Domains\\Product\\Models\\ProductBundle/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\PricingRule\b/App\\Domains\\Product\\Models\\PricingRule/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\SubscriptionPlan\b/App\\Domains\\Product\\Models\\SubscriptionPlan/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Ticket\b/App\\Domains\\Ticket\\Models\\Ticket/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\TicketComment\b/App\\Domains\\Ticket\\Models\\TicketComment/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\TicketReply\b/App\\Domains\\Ticket\\Models\\TicketComment/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\TicketWatcher\b/App\\Domains\\Ticket\\Models\\TicketWatcher/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\TicketTimeEntry\b/App\\Domains\\Ticket\\Models\\TicketTimeEntry/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\TicketRating\b/App\\Domains\\Ticket\\Models\\TicketRating/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\TimeEntry\b/App\\Domains\\Ticket\\Models\\TimeEntry/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Project\b/App\\Domains\\Project\\Models\\Project/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Vendor\b/App\\Domains\\Project\\Models\\Vendor/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Contract\b/App\\Domains\\Contract\\Models\\Contract/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\ContractConfiguration\b/App\\Domains\\Contract\\Models\\ContractConfiguration/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\ContractClause\b/App\\Domains\\Contract\\Models\\ContractClause/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\ContractActionButton\b/App\\Domains\\Contract\\Models\\ContractActionButton/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Tax\b/App\\Domains\\Tax\\Models\\Tax/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\TaxCategory\b/App\\Domains\\Tax\\Models\\TaxCategory/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\TaxJurisdiction\b/App\\Domains\\Tax\\Models\\TaxJurisdiction/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\TaxExemption\b/App\\Domains\\Tax\\Models\\TaxExemption/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\TaxCalculation\b/App\\Domains\\Tax\\Models\\TaxCalculation/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\VoIPTaxRate\b/App\\Domains\\Tax\\Models\\VoIPTaxRate/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\ComplianceRecord\b/App\\Domains\\Tax\\Models\\ComplianceCheck/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Lead\b/App\\Domains\\Lead\\Models\\Lead/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\Integration\b/App\\Domains\\Integration\\Models\\Integration/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\RmmIntegration\b/App\\Domains\\Integration\\Models\\RmmIntegration/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\RmmClientMapping\b/App\\Domains\\Integration\\Models\\RmmClientMapping/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\KbArticle\b/App\\Domains\\Knowledge\\Models\\KbArticle/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\PhysicalMailSettings\b/App\\Domains\\PhysicalMail\\Models\\PhysicalMailSettings/g' {} +
find app database resources tests scripts -type f -name "*.php" -exec sed -i 's/App\\Models\\DunningCampaign\b/App\\Domains\\Collections\\Models\\DunningCampaign/g' {} +
echo "Done! Verifying remaining App\\Models references:"
rg "App\\\\Models\\\\" --type php | grep -v vendor | grep -v _ide_helper | wc -l
