<?php

namespace Database\Seeders\Dev;

use Illuminate\Database\Seeder;
use App\Models\Company;

class CompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->command->info('Creating companies...');

        $companies = [
            [
                'id' => 1,
                'name' => 'Nestogy Platform',
                'address' => '100 Tech Plaza',
                'city' => 'San Francisco',
                'state' => 'CA',
                'zip' => '94105',
                'country' => 'USA',
                'phone' => '(415) 555-0100',
                'email' => 'admin@nestogy.com',
                'website' => 'https://nestogy.com',
                'locale' => 'en_US',
                'currency' => 'USD',
                'is_active' => true,
                'company_type' => 'root',
                'organizational_level' => 0,
                'default_standard_rate' => 200.00,
                'default_after_hours_rate' => 300.00,
                'default_emergency_rate' => 400.00,
                'default_weekend_rate' => 250.00,
                'default_holiday_rate' => 350.00,
                'after_hours_multiplier' => 1.5,
                'emergency_multiplier' => 2.0,
                'weekend_multiplier' => 1.25,
                'holiday_multiplier' => 1.75,
                'rate_calculation_method' => 'multipliers',
                'minimum_billing_increment' => 15,
                'time_rounding_method' => 'up',
                'can_create_subsidiaries' => true,
                'max_subsidiary_depth' => 3,
                'billing_type' => 'independent',
            ],
            [
                'id' => 2,
                'name' => 'TechGuard MSP',
                'address' => '500 Business Center Dr',
                'city' => 'New York',
                'state' => 'NY',
                'zip' => '10001',
                'country' => 'USA',
                'phone' => '(212) 555-0200',
                'email' => 'info@techguardmsp.com',
                'website' => 'https://techguardmsp.com',
                'locale' => 'en_US',
                'currency' => 'USD',
                'is_active' => true,
                'company_type' => 'subsidiary',
                'organizational_level' => 1,
                'default_standard_rate' => 175.00,
                'default_after_hours_rate' => 262.50,
                'default_emergency_rate' => 350.00,
                'default_weekend_rate' => 218.75,
                'default_holiday_rate' => 306.25,
                'after_hours_multiplier' => 1.5,
                'emergency_multiplier' => 2.0,
                'weekend_multiplier' => 1.25,
                'holiday_multiplier' => 1.75,
                'rate_calculation_method' => 'multipliers',
                'minimum_billing_increment' => 15,
                'time_rounding_method' => 'up',
                'can_create_subsidiaries' => false,
                'billing_type' => 'independent',
            ],
            [
                'id' => 3,
                'name' => 'CloudFirst Solutions',
                'address' => '1200 Innovation Way',
                'city' => 'Chicago',
                'state' => 'IL',
                'zip' => '60601',
                'country' => 'USA',
                'phone' => '(312) 555-0300',
                'email' => 'info@cloudfirstsolutions.com',
                'website' => 'https://cloudfirstsolutions.com',
                'locale' => 'en_US',
                'currency' => 'USD',
                'is_active' => true,
                'company_type' => 'subsidiary',
                'organizational_level' => 1,
                'default_standard_rate' => 150.00,
                'default_after_hours_rate' => 225.00,
                'default_emergency_rate' => 300.00,
                'default_weekend_rate' => 187.50,
                'default_holiday_rate' => 262.50,
                'after_hours_multiplier' => 1.5,
                'emergency_multiplier' => 2.0,
                'weekend_multiplier' => 1.25,
                'holiday_multiplier' => 1.75,
                'rate_calculation_method' => 'multipliers',
                'minimum_billing_increment' => 15,
                'time_rounding_method' => 'up',
                'can_create_subsidiaries' => false,
                'billing_type' => 'independent',
            ],
            [
                'id' => 4,
                'name' => 'Digital Shield IT',
                'address' => '789 Tech Boulevard',
                'city' => 'Los Angeles',
                'state' => 'CA',
                'zip' => '90001',
                'country' => 'USA',
                'phone' => '(310) 555-0400',
                'email' => 'info@digitalshieldit.com',
                'website' => 'https://digitalshieldit.com',
                'locale' => 'en_US',
                'currency' => 'USD',
                'is_active' => true,
                'company_type' => 'subsidiary',
                'organizational_level' => 1,
                'default_standard_rate' => 200.00,
                'default_after_hours_rate' => 300.00,
                'default_emergency_rate' => 400.00,
                'default_weekend_rate' => 250.00,
                'default_holiday_rate' => 350.00,
                'after_hours_multiplier' => 1.5,
                'emergency_multiplier' => 2.0,
                'weekend_multiplier' => 1.25,
                'holiday_multiplier' => 1.75,
                'rate_calculation_method' => 'multipliers',
                'minimum_billing_increment' => 15,
                'time_rounding_method' => 'up',
                'can_create_subsidiaries' => false,
                'billing_type' => 'independent',
            ],
            [
                'id' => 5,
                'name' => 'Mountain Peak Tech',
                'address' => '2500 Summit Avenue',
                'city' => 'Denver',
                'state' => 'CO',
                'zip' => '80201',
                'country' => 'USA',
                'phone' => '(303) 555-0500',
                'email' => 'info@mountainpeaktech.com',
                'website' => 'https://mountainpeaktech.com',
                'locale' => 'en_US',
                'currency' => 'USD',
                'is_active' => true,
                'company_type' => 'subsidiary',
                'organizational_level' => 1,
                'default_standard_rate' => 225.00,
                'default_after_hours_rate' => 337.50,
                'default_emergency_rate' => 450.00,
                'default_weekend_rate' => 281.25,
                'default_holiday_rate' => 393.75,
                'after_hours_multiplier' => 1.5,
                'emergency_multiplier' => 2.0,
                'weekend_multiplier' => 1.25,
                'holiday_multiplier' => 1.75,
                'rate_calculation_method' => 'multipliers',
                'minimum_billing_increment' => 15,
                'time_rounding_method' => 'up',
                'can_create_subsidiaries' => false,
                'billing_type' => 'independent',
            ],
            [
                'id' => 6,
                'name' => 'CyberSecure Partners',
                'address' => '900 Security Way',
                'city' => 'Austin',
                'state' => 'TX',
                'zip' => '78701',
                'country' => 'USA',
                'phone' => '(512) 555-0600',
                'email' => 'info@cybersecurepartners.com',
                'website' => 'https://cybersecurepartners.com',
                'locale' => 'en_US',
                'currency' => 'USD',
                'is_active' => true,
                'company_type' => 'subsidiary',
                'organizational_level' => 1,
                'default_standard_rate' => 250.00,
                'default_after_hours_rate' => 375.00,
                'default_emergency_rate' => 500.00,
                'default_weekend_rate' => 312.50,
                'default_holiday_rate' => 437.50,
                'after_hours_multiplier' => 1.5,
                'emergency_multiplier' => 2.0,
                'weekend_multiplier' => 1.25,
                'holiday_multiplier' => 1.75,
                'rate_calculation_method' => 'multipliers',
                'minimum_billing_increment' => 15,
                'time_rounding_method' => 'up',
                'can_create_subsidiaries' => false,
                'billing_type' => 'independent',
            ],
            [
                'id' => 7,
                'name' => 'Infinity IT Solutions',
                'address' => '1500 Enterprise Pkwy',
                'city' => 'Seattle',
                'state' => 'WA',
                'zip' => '98101',
                'country' => 'USA',
                'phone' => '(206) 555-0700',
                'email' => 'info@infinityitsolutions.com',
                'website' => 'https://infinityitsolutions.com',
                'locale' => 'en_US',
                'currency' => 'USD',
                'is_active' => true,
                'company_type' => 'subsidiary',
                'organizational_level' => 1,
                'default_standard_rate' => 190.00,
                'default_after_hours_rate' => 285.00,
                'default_emergency_rate' => 380.00,
                'default_weekend_rate' => 237.50,
                'default_holiday_rate' => 332.50,
                'after_hours_multiplier' => 1.5,
                'emergency_multiplier' => 2.0,
                'weekend_multiplier' => 1.25,
                'holiday_multiplier' => 1.75,
                'rate_calculation_method' => 'multipliers',
                'minimum_billing_increment' => 15,
                'time_rounding_method' => 'up',
                'can_create_subsidiaries' => false,
                'billing_type' => 'independent',
            ],
            [
                'id' => 8,
                'name' => 'ProTech Managed Services',
                'address' => '750 Tech Park Dr',
                'city' => 'Boston',
                'state' => 'MA',
                'zip' => '02101',
                'country' => 'USA',
                'phone' => '(617) 555-0800',
                'email' => 'info@protechmsp.com',
                'website' => 'https://protechmsp.com',
                'locale' => 'en_US',
                'currency' => 'USD',
                'is_active' => true,
                'company_type' => 'subsidiary',
                'organizational_level' => 1,
                'default_standard_rate' => 185.00,
                'default_after_hours_rate' => 277.50,
                'default_emergency_rate' => 370.00,
                'default_weekend_rate' => 231.25,
                'default_holiday_rate' => 323.75,
                'after_hours_multiplier' => 1.5,
                'emergency_multiplier' => 2.0,
                'weekend_multiplier' => 1.25,
                'holiday_multiplier' => 1.75,
                'rate_calculation_method' => 'multipliers',
                'minimum_billing_increment' => 15,
                'time_rounding_method' => 'up',
                'can_create_subsidiaries' => false,
                'billing_type' => 'independent',
            ],
        ];

        foreach ($companies as $companyData) {
            Company::updateOrCreate(
                ['id' => $companyData['id']],
                $companyData
            );
            $this->command->info("  ✓ Created company: {$companyData['name']}");
        }

        $this->command->info('Companies created successfully.');
    }
}