name: CI

on:
  - pull_request
  - push

jobs:
  tests:
    name: Tests

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: nestogy_test
          POSTGRES_USER: nestogy
          POSTGRES_PASSWORD: nestogy_test_pass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: xdebug
          extensions: pgsql, pdo_pgsql

      - name: Configure Flux Pro credentials
        env:
          FLUX_USERNAME: ${{ secrets.FLUX_USERNAME }}
          FLUX_LICENSE_KEY: ${{ secrets.FLUX_PRO_TOKEN }}
        run: |
          echo "{\"http-basic\":{\"composer.fluxui.dev\":{\"username\":\"${FLUX_USERNAME}\",\"password\":\"${FLUX_LICENSE_KEY}\"}}}" > auth.json

      - name: Install dependencies with composer
        run: composer install --no-ansi --no-interaction --no-progress --prefer-dist --no-scripts

      - name: Run tests with phpunit/phpunit
        env:
          APP_KEY: base64:test1234567890123456789012345678901234567890123=
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: nestogy_test
          DB_USERNAME: nestogy
          DB_PASSWORD: nestogy_test_pass
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
